name: continuous-integration
on: [pull_request]
jobs:
  test-runner:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - name: "Base istanbul/tape node tests"
      run: npm test
    - name: "Benchmark tests"
      run: npm run benchmark
    - name: "Gif tests"
      run: npm run gif-test
    - name: "Browserify core tests and run"
      run: grunt tests && npm run core-tests
    - name: "Jasmine UI tests (mocked browser env)"
      run: npm run test-ui
    - name: "jest-puppeteer UI tests (full browser env)"
      run: npm run test-ui-2    
    - name: "CLI tests"
      run: npm run test-cli
    - name: "Grunt build test of dev environment"
      run: grunt build

## Cache NPM folder
# cache:
#   directories:
#     - ~/.npm
#     - ~/.cache
