name: continuous-integration
on: [pull_request]
jobs:
  test-runner:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    -
    - name: Install prerequisites
      run: | 
       sudo apt-get install g++-4.8 xvfb
       sudo apt-get install xserver-xorg-dev libxext-dev libxi-dev 
       sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config libglu1-mesa-dev freeglut3-dev mesa-common-dev 
       export DISPLAY=':99.0' # for tape-run 
       Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & # for tape-run 
    - run: npm install
    - name: "Base istanbul/tape node tests"
      run: npm test
    - name: "Benchmark tests"
      run: npm run benchmark
    - name: "Gif tests"
      run: npm run gif-test
    - name: "Browserify core tests and run"
      run: grunt tests && npm run core-tests
    - name: "Jasmine UI tests (mocked browser env)"
      run: npm run test-ui
    - name: "jest-puppeteer UI tests (full browser env)"
      run: npm run test-ui-2    
    - name: "CLI tests"
      run: npm run test-cli
    - name: "Grunt build test of dev environment"
      run: grunt build

## Cache NPM folder
# cache:
#   directories:
#     - ~/.npm
#     - ~/.cache
